---
- hosts: localhost
  tasks:
  - name: "hello"
    azure_rm_deployment:
      state: present
      resource_group_name: djjj
      template_link: "https://raw.githubusercontent.com/medhanoo/tower-test/master/temp.json"
      parameters:
        databaseName:
          value: abc
        maxSizeBytes: 
          value: 268435456000
        skuName: 
          value: S1
        sampleName: 
          value: ""
        zoneRedundant: 
          value: False
        licenseType: 
          value: ""
        location: 
          value: "Central US"
        EngagementId: 
          value: "xx"
        Owner:  
          value: "xx"
        DeploymentID: 
          value: "xx"
        serverName: 
          value: "asasa"
        tier: 
          value: "standard"
        
        
