---
- name: Test Play
  hosts: all
  tasks:
  - name: "Demo string"
    debug:
      msg: "Heya"

  - name: "whoami"
    shell: "whoami"
    register: out

  - name: "whoami out string"
    debug:
      msg: "{{ out }}"

